# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clu < Formula
  desc "A terminal interface for the commandlineuser.com CLI catalogue"
  homepage "https://commandlineuser.com"
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ali5ter/clu/releases/download/v1.1.3/clu_darwin_amd64.tar.gz"
      sha256 "b7c30f08b72a097a96e96a4ac389c94417b6aef3aa68d969ba3fee8a788f5f0f"

      define_method(:install) do
        bin.install "clu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ali5ter/clu/releases/download/v1.1.3/clu_darwin_arm64.tar.gz"
      sha256 "298dd6c96292fc995d55a24603bba949df1bba25d345e79c90b34e983a371437"

      define_method(:install) do
        bin.install "clu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/clu/releases/download/v1.1.3/clu_linux_amd64.tar.gz"
      sha256 "551b2e1e265f573836f8427fd723cb9f2db12a5c9156e31a82d42304d334b880"
      define_method(:install) do
        bin.install "clu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ali5ter/clu/releases/download/v1.1.3/clu_linux_arm64.tar.gz"
      sha256 "54abda1195243b5a9a525d82792b02b6f77e711271b56b9f5c0d406cbf8382f9"
      define_method(:install) do
        bin.install "clu"
      end
    end
  end

  test do
    system "#{bin}/clu", "--version"
  end
end
